// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieGallery_API.Models.stage_jacopo;

public partial class Movies
{
    public int MovieID { get; set; }

    public string Title { get; set; }

    public int? Year { get; set; }

    public string Cast { get; set; }

    public string Genres { get; set; }

    public string Href { get; set; }

    public string Description { get; set; }

    public string Thumbnail { get; set; }

    public int? Thumbnail_Width { get; set; }

    public int? Thumbnail_Height { get; set; }
}