// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MovieGallery_API.Models.stage_jacopo;

public partial class stage_jacopoContext : DbContext
{
    public stage_jacopoContext()
    {
    }

    public stage_jacopoContext(DbContextOptions<stage_jacopoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Movies> Movies { get; set; }

    public virtual DbSet<Users> Users { get; set; }

 
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Movies>(entity =>
        {
            entity.HasKey(e => e.MovieID).HasName("PK__Movies__4BD2943A5FBAFB20");

            entity.Property(e => e.MovieID).ValueGeneratedNever();
            entity.Property(e => e.Href).HasMaxLength(255);
            entity.Property(e => e.Thumbnail).HasMaxLength(500);
            entity.Property(e => e.Title).HasMaxLength(255);
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.UserID);

            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}