// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieGallery_API.Models.stage_jacopo;

public partial class Users
{
    public int UserID { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string UserType { get; set; }
}